#! /bin/sh

bspc monitor -d     

bspc config border_width         $(echo 3 \* $GDK_SCALE | bc)
bspc config window_gap           $(echo 12 \* $GDK_SCALE | bc)

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config single_monocle        true
bspc config focus_follows_pointer true
bspc config focused_border_color  '#8E83B8'
bspc config normal_border_color   '#51425C'

bspc rule -a "*:transgui"                      state=pseudo_tiled follow=on
bspc rule -a "*:anydesk"                       state=pseudo_tiled follow=on
#bspc rule -a Code                 desktop='^4'                    follow=on
bspc rule -a Brave-browser       desktop='^3'                    follow=on
bspc rule -a TelegramDesktop                   state=floating     sticky=on
bspc rule -a baka-mplayer                      state=floating     sticky=on
bspc rule -a smplayer                          state=floating     sticky=on
bspc rule -a "*:org.gnome.Nautilus"            state=pseudo_tiled follow=on
bspc config external_rules_command $HOME/.config/bspwm/external-rules.sh

dex -a

sxhkd &
