#!/bin/sh

export DESKTOP_SESSION="bspwm"

# load xprofile
[[ -f /etc/xprofile ]] && . /etc/xprofile
[[ -f ~/.xprofile ]] && . ~/.xprofile

# load xmodmap
[[ -f ~/.Xmodmap ]] && xmodmap ~/.Xmodmap

# load xresources
[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

dunst &
picom &
$HOME/.fehbg
xsetroot -cursor_name left_ptr
picom --experimental-backends &
libinput-gestures-setup restart
polybar -r mybar &

# subscribers
$HOME/.config/bspwm/layout_monitor.sh &
$HOME/.config/bspwm/udev_monitor.sh &

exec bspwm
