export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME='vbalien'
ZSH_CUSTOM=$HOME/.config/ohmyzsh

plugins=(git)

source $ZSH/oh-my-zsh.sh

###
# User configuration
###

# Environment variables
export PATH="$HOME/.local/bin:$HOME/.deno/bin:$HOME/.yarn/bin:$PATH"
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'
export DOCKER_HOST="unix://$XDG_RUNTIME_DIR/podman/podman.sock"

# Preferred editor for local and remote sessions
export EDITOR='vim'

# aliases
alias vim='nvim'
alias sudo='sudo '

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

ufetch
